name: Deploy to Linux
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up GraalVM 19.3.0 / Java 11
      uses: rtc11/setup-graalvm@master
      with:
        args: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.0/graalvm-ce-java11-linux-amd64-19.3.0.tar.gz
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Build distribution
      env:
        GRAALVM_HOME=/home/runner/work/client-samples/client-samples/graalvm
      run: export JAVA_HOME=/home/runner/work/client-samples/client-samples/graalvm; set ; cd Maven/HelloWorld ; mvn clean client:build ; ls target
