name: Deploy to Linux
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up GraalVM 19.3.0 / Java 11
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.0.java11'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    
    - name: Build distribution
      run: cd Maven/HelloWorld ; mvn clean client:build ; ls target
